# This will execute some scripts on main branch.

name: TagRun

on:
  push:
    tags:
      - '*'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  runme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout current repo
      uses: actions/checkout@v3

    - uses: actions-ecosystem/action-get-latest-tag@v1
      id: get-latest-tag

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ steps.get-latest-tag.outputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: capture changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.0.1
      with:
        myToken: ${{ secrets.GITHUB_TOKEN }}

    - name: sbt ci-publish-github
      run: sbt compile publish

    - name: ci-release-github
      id: create-release
      uses: actions/create-release@latest
      with:
        allowUpdates: true
        tag_name: ${{ steps.get-latest-tag.outputs.tag }}
        release_name: Release ${{ steps.get-latest-tag.outputs.tag }}
        body: |
          ## What's Changed
          ${{ steps.changelog.outputs.changelog }}
        draft: false
        prerelease: false
