# This will execute some scripts on main branch.

name: MasterRun

on:
  push:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  runme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout dj-wasabi-release repo
      uses: actions/checkout@v3
      with:
        repository: dj-wasabi/dj-wasabi-release
        path: dj-wasabi-release

    - name: Checkout current repo
      uses: actions/checkout@v3
      with:
        path: main
        fetch-depth: 0

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: main/
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Commit Changelog file
      run: |
        # We are cloned in the 'main' directory and the dj-wasabi-release
        # repository is the 'dj-wasabi-release' next to 'main'
        cd main

        # Generate CHANGELOG.md file
        ../dj-wasabi-release/release.sh -d

        # Let commit the changes if there are any? (Well there should be!)
        if [[ $(git status | grep -c 'CHANGELOG.md' || true) -gt 0 ]]
          then  echo "Committing file"
                git config --global user.name 'Werner Dijkerman [GH bot]'
                git config --global user.email 'github@dj-wasabi.nl'

                git add CHANGELOG.md
                git commit -m "Updated CHANGELOG.md on \"$(date "+%Y-%m-%d %H:%M:%S")\"" CHANGELOG.md
                git push
        fi
      env:
        CHANGELOG_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
