name: Python test_djWasabi

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -r src/requirements.txt
        python -m pip install -r src/requirements-dev.txt

    - name: Execute unit tests
      run: |
        export VERSIONDB_ENVIRONMENT=ci
        pytest src/tests/unit -vvv

    - name: Execute Functional tests
      run: |
        export VERSIONDB_ENVIRONMENT=ci
        pytest src/tests/functional -vvv
